---
- hosts: spark-cluster
  remote_user: ubuntu
  sudo: yes
  tasks:
  - name: Copy contents of spark template to its own file
    shell: cp /home/ubuntu/spark-1.3.1-bin-hadoop2.6/conf/spark-env.sh.template /home/ubuntu/spark-1.3.1-bin-hadoop2.6/conf/spark-env.sh
  - name: Append contents of spark-env.txt to spark-env.sh
    shell: cat /home/ubuntu/spark-env.txt > /home/ubuntu/spark-1.3.1-bin-hadoop2.6/conf/spark-env.sh
  - name: Source spark-env
    shell: . /home/ubuntu/spark-1.3.1-bin-hadoop2.6/conf/spark-env.sh
 
